name: admin_dashboard
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.3
  dio: ^5.8.0+1
  flutter_spinkit: ^5.2.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  gap: ^3.0.1
  flutter_svg: ^2.2.0
  audioplayers: ^6.5.0
  intl: ^0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.5.2
  flutter_gen_runner: ^5.10.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

    # Optional
  integrations:
    flutter_svg: true
    rive: true
    lottie: true

  assets:
    exclude:
      [
        assets/image/1.5x/*,
        assets/image/2.0x/*,
        assets/image/3.0x/*,
        assets/image/4.0x/*,
      ]

  colors:
    inputs:
      - assets/colors/colors.xml

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/svgs/