// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJlUk4V4FGoS9zUW4oo74hxznnaPrcxJo',
    appId: '1:887192895309:web:2534e0102674c9622c4104',
    messagingSenderId: '887192895309',
    projectId: 'app-audio-analyzer',
    authDomain: 'app-audio-analyzer.firebaseapp.com',
    storageBucket: 'app-audio-analyzer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_26jbsh-P0Pg80dpagDuSuCTFCk4aj5A',
    appId: '1:887192895309:android:aff93361d09f89e62c4104',
    messagingSenderId: '887192895309',
    projectId: 'app-audio-analyzer',
    storageBucket: 'app-audio-analyzer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk9waNwlNipHy8g1vnVVbiZcBvVwN4tgs',
    appId: '1:887192895309:ios:f866f0df689735fb2c4104',
    messagingSenderId: '887192895309',
    projectId: 'app-audio-analyzer',
    storageBucket: 'app-audio-analyzer.firebasestorage.app',
    androidClientId: '887192895309-5vo87cu4sht ghfabrgcptkf1c8arm8ib.apps.googleusercontent.com',
    iosClientId: '887192895309-8p8h4nvv692lkemqu8c4cfhmfqnvive7.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk9waNwlNipHy8g1vnVVbiZcBvVwN4tgs',
    appId: '1:887192895309:ios:f866f0df689735fb2c4104',
    messagingSenderId: '887192895309',
    projectId: 'app-audio-analyzer',
    storageBucket: 'app-audio-analyzer.firebasestorage.app',
    androidClientId: '887192895309-5vo87cu4shtghfabrgcptkf1c8arm8ib.apps.googleusercontent.com',
    iosClientId: '887192895309-8p8h4nvv692lkemqu8c4cfhmfqnvive7.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJlUk4V4FGoS9zUW4oo74hxznnaPrcxJo',
    appId: '1:887192895309:web:2b01e9bf9d3901542c4104',
    messagingSenderId: '887192895309',
    projectId: 'app-audio-analyzer',
    authDomain: 'app-audio-analyzer.firebaseapp.com',
    storageBucket: 'app-audio-analyzer.firebasestorage.app',
  );
}
